<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>KSoft.Blam</RootNamespace>
    <AssemblyName>KSoft.Blam</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(VitaRootDir)\KSoft\KSoft\KSoft.csproj">
      <Project>{eb07f515-e27c-4768-8bd8-2829f657807e}</Project>
      <Name>KSoft</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Compression\KSoft.Compression.csproj">
      <Project>{0b27603c-ceb1-4a3a-b56f-cbc14b8c06e7}</Project>
      <Name>KSoft.Compression</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)\KSoft\KSoft.IO.TagElementStreams\KSoft.IO.TagElementStreams.csproj">
      <Project>{18f32228-8351-4f99-992f-78e9d1ce83d9}</Project>
      <Name>KSoft.IO.TagElementStreams</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)\KSoft\KSoft.Security\KSoft.Security.csproj">
      <Project>{0632a00b-de9e-4350-a3f8-3a82f9c780af}</Project>
      <Name>KSoft.Security</Name>
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Engine\EngineRegistry.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo1\Halo1.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo2\Halo2.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo2\Halo2_Localization.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo3\Halo3.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo3\Halo3_Localization.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo4\Halo4.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo4\Halo4_Localization.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo4\Halo4_Blobs.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo4\Halo4_Megalo.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo4\Megalo\Proto\Halo4_MegaloStaticDb_Xbox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\Halo4\Megalo\Proto\Halo4_MegaloDb_Xbox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <Content Include="Games\HaloReach\HaloReach.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\HaloReach\HaloReach_Blobs.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\HaloReach\HaloReach_Localization.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\HaloReach\HaloReach_Megalo.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\HaloReach\Megalo\Proto\HaloReach_MegaloStaticDb_Xbox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Games\HaloReach\Megalo\Proto\HaloReach_MegaloDb_Xbox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <Content Include="Localization\LanguageRegistry.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
